tasks:
  - cls: SimpleFFTSource
    currency: 1
    locate: satellite1
  - cls: FFTOp
    currency: 1
    input_tasks: [HttpSource]
    locate: satellite1
  - cls: HaFilterOp
    currency: 1
    input_tasks: [FFTOp]
    locate: satellite1
  - cls: HaSumOp
    currency: 1
    input_tasks: [HaFilterOp]
    locate: satellite1
  - cls: SimpleSink
    currency: 1
    input_tasks: [HaSumOp]
    locate: satellite1
