tasks:
  - cls: SimpleFFTSource
    currency: 1
  - cls: FFTOp
    currency: 1
    input_tasks:
      - SimpleFFTSource
  - cls: HaFilterOp
    currency: 1
    input_tasks:
      - FFTOp
  - cls: HaSumOp
    currency: 1
    input_tasks:
      - HaFilterOp
  - cls: SimpleFFTSink
    currency: 1
    input_tasks:
      - HaSumOp
