tasks:
  - cls: SimpleSource
    currency: 1
    locate: 1
  - cls: KeyByInputOp
    currency: 1
    input_tasks: [SimpleSource]
    locate: 1
  - cls: SumOp
    currency: 2
    input_tasks: [KeyByInputOp]
    locate: 1
  - cls: SimpleSink
    currency: 1
    input_tasks: [SumOp]
    locate: 1
