image: harbor.act.buaa.edu.cn/satweave/rocksdb-go:6.28.2-alpine
stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - docker-build
#  - deploy
#  - benchmark

variables:
  DOCKER_REGISTRY: harbor.act.buaa.edu.cn
  DOCKERHUB_NAMESPACE: satweave
  BRANCH_NAME: $CI_COMMIT_REF_NAME
  COMMIT_SHA: $CI_COMMIT_SHA

before_script:
  - export GOPATH=$GOPATH:/usr/local/${CI_PROJECT_NAME}
  - export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}:/usr/local/lib/rocksdb
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
  - export LIBRARY_PATH=${LIBRARY_PATH}:/usr/local/lib
  - export VERSION=`echo ${CI_COMMIT_TAG} | awk -F"_" '{print $1}'`
  - export GO111MODULE=on
  - export GOPROXY=https://goproxy.cn,direct

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - go env -w GOMODCACHE=$(pwd)/.mod_cache/ GOPROXY=https://goproxy.cn,direct GOCACHE=$(pwd)/.go_cache/
  script:
    - echo "Compiling the code..."
    - export CGO_CFLAGS="-I/usr/local/lib"
    - export CGO_LDFLAGS="-L/usr/local/lib -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy -llz4 -lzstd"
    - go mod tidy
#    - go build -o build/bin/satweave
#    - go build -o build/bin/satweave-client satweave/cli
#    - go build -o build/bin/satweave-cloud satweave/cloud
    - go build -o build/bin/satweave-edge-node satweave/sat-node
    - echo "Compile complete."
  artifacts:
    paths:
      - build/
    when: always
    expire_in: 1 weeks
#  cache:
#    key: ecos_go_env # 干嘛用的？
#    paths:
#      - .mod_cache/
#      - .go_cache/

unit-test-job:   # This job runs in the test stage.
  stage: test
  needs: []
  script:
    - go env -w GOMODCACHE=$(pwd)/.mod_cache/ GOPROXY=https://goproxy.cn,direct GOCACHE=$(pwd)/.go_cache/
    - echo "Running unit tests..."
#    - golangci-lint --version
#    - golangci-lint run --out-format checkstyle ./... > report.xml & # run in background
    - go mod tidy
    - go test ./...  -coverprofile=cover.out -race -timeout=4m  # enable race test default
    - ls
  artifacts:
    paths:
      - cover.out
      - report.xml
    when: always
    expire_in: 8 weeks
#  cache:
#    key: ecos_go_env
#    paths:
#      - .mod_cache/
#      - .go_cache/

satweave-docker-build:
  stage: docker-build
  needs: [build-job]
  #  needs: [build-job, unit-test-job]
  image: docker:19.03.0
  #  services:
  #    - docker:19.03.0-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://localhost:2375
  before_script:
    - docker info
    - docker login -u qiutb -p qtb@ACT.123 harbor.act.buaa.edu.cn
    - export BUILD_NUMBER=${COMMIT_SHA:0:5}
  script:
    - mv ./build ./Dockerfile
    - mv ./conf ./Dockerfile
    - cd Dockerfile
    - ls ./build/bin
    - - echo "build satweave-client docker image"