---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: satweave-client-dev-v1
  namespace: satweave
  labels:
    app: satweave-client-dev-v1
  annotations:
    deployment.kubernetes.io/revision: '4'
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satweave-client-dev-v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: satweave-client-dev-v1
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"10.244.3.101\"]"
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-hobwav
          persistentVolumeClaim:
            claimName: satweave-client-storage
      containers:
        - name: satweave-client-pod
          image: 'harbor.act.buaa.edu.cn/satweave/satweave-client:SNAPSHOT-latest'
          command:
            - tail
            - '-f'
          args:
            - /dev/null
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-hobwav
              mountPath: /data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      imagePullSecrets:
        - name: harbor-act
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satweave-client-storage
  namespace: satweave
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
